[package]
name = "candle-nn"
version = "0.1.0"
edition = "2021"

[dependencies]
candle = { version = "0.4", package = "candle-core" }
candle-nn = { version = "0.4" }
tqdm = "0.6"

[profile.dev.package."*"]
opt-level = 3

[features]
cuda = ["candle/cuda"]